### ISSUE TITLE
[Hubitat] Aeon Smartstrip java.lang.NumberFormatException: null on line 250 (parse)

### ISSUE THREAD

**Issue by tkdrob** [erocm123/Hubitat#11]
@erocm123 Not sure how to solve this

**Comment by tkdrob** [comment]
I'm trying to get power metering to work for hubitat as well

**Comment by erocm123** [comment]
I don't have this device anymore, so I'm kind of shooting in the dark. Can you test the latest driver?

**Comment by tkdrob** [comment]
No dice. I think I read somewhere there is a bug with the latest hub firmware. I've contacted support to ask if they can provide me with their stock driver code for this device. Maybe their methods are different

**Comment by tkdrob** [comment]
null is now on line 250 btw

**Comment by InovelliUSA** [comment]
Ok, I did find a strip in my basement. Something isn't right about how it is reporting in Hubitat:

Invalid Energy Report: MeterReport(meterType: 1, precision: 3, scale: 2, size: 4, meterValue: [], rateType: 1, deltaTime: 0, previousMeterValue: [])

There is missing information in this report. May be a bug in Hubitat.

**Comment by erocm123** [comment]
Ok, I did find a strip in my basement. Something isn't right about how it is reporting in Hubitat:

Invalid Energy Report: MeterReport(meterType: 1, precision: 3, scale: 2, size: 4, meterValue: [], rateType: 1, deltaTime: 0, previousMeterValue: [])

There is missing information in this report. May be a bug in Hubitat.

**Comment by erocm123** [comment]
Closing this as Hubitat still isn't seeing the meterValue for power reports. I've seen this on another device as well. I've added error handling to stop the error message but the power readings will always show as 0.
