### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by mordorf** [erocm123/Hubitat#14]
Getting the below error.
I have configured the app to just monitor two devices to see if it was a bad device but problem persists.

`java.lang.NullPointerException: Cannot invoke method toInteger() on null object on line 433 (pageStatus)`

**Comment by InovelliUSA** [comment]
What are your battery settings in the app and what is the value of the "battery" state of the devices you are monitoring?

![image](https://user-images.githubusercontent.com/37669481/89448084-4b3f9f80-d714-11ea-9255-7496d66fd196.png)

**Comment by erocm123** [comment]
What are your battery settings in the app and what is the value of the "battery" state of the devices you are monitoring?

![image](https://user-images.githubusercontent.com/8661384/89451341-492c0f80-d719-11ea-8746-30ef20bf7868.png)

**Comment by mordorf** [comment]
All sorted now. Think I just added an unsupported cloud device. 
Thanks :-)
