### ISSUE TITLE
Does Hubitat device input support 'paragraph' type and 'element' option?

### ISSUE THREAD

**Issue by biocomp** [erocm123/Hubitat#3]
Here:
https://github.com/erocm123/Hubitat/blob/f366c303bac7dff7f76ddb677e01b2420c66bd7d/Drivers/fibaro-double-switch-2-fgs-223.src/fibaro-double-switch-2-fgs-223.groovy#L490-L491

Hubitat docs are, well, far from perfect. But looking at SmartThings [docs](https://docs.smartthings.com/en/latest/device-type-developers-guide/device-preferences.html#supported-input-types), doesn't look like device input() type 'paragraph' is supported, as well as option 'element'.

It obviously does load successfully in Hubitat, but are you sure that's what you meant?
If so, could you explain what they achieve as opposed to using type 'text' and removing 'element' option? This is mostly for my education.

Thanks!

**Comment by erocm123** [comment]
This is a SmartThings handler that was converted for Hubitat. SmartThings has the undocumented "paragraph" preference type. It seems to work in Hubitat too but has an input line. If there is a better way to display information in the preferences section I haven't yet found it.

**Comment by biocomp** [comment]
Seems like 'type: "text'" works as "well". But SmartThings had "paragraph" working, and it works in Hubitat too, I'm not sure what's the best thing to do here. One could hope Hubitat would have "paragraph" supported in the future.
Maybe just remove "element"? Or was it needed in SmartThings to work?

**Comment by biocomp** [comment]
Also, do you want more issues or pull requests with fixes like this one in the future?

**Comment by erocm123** [comment]
Pull requests would be great. Thanks.
