### ISSUE TITLE
displayDuringSetup gets value of "" instead true or false.

### ISSUE THREAD

**Issue by biocomp** [erocm123/Hubitat#4]
Because they're not in the xml.

https://github.com/erocm123/Hubitat/blob/f366c303bac7dff7f76ddb677e01b2420c66bd7d/Drivers/fibaro-double-switch-2-fgs-223.src/fibaro-double-switch-2-fgs-223.groovy#L463

Again, I guess this is working OK, but is this really what you intended? Looks like removing 'displayDuringSetup' from the switch statement could be a good idea?

**Comment by erocm123** [comment]
Yeah, you are right. It doesn't cause any problems but doesn't need to be there.
