### ISSUE TITLE
No longer getting temp reports

### ISSUE THREAD

**Issue by bmcgair** [erocm123/Hubitat#5]
https://community.hubitat.com/t/qbino-flush-1d-temp-report-no-longer-updating/13061

Hi. I'm no longer getting temp reports from my qubino-flush-1D. Was working for the last year or so but broke in the last week or 2. The only time I get a temp update is if I push a config parameter change.

I noticed you had a comment about hubitat not parsing the reports properly and wondered if this could be related? I did update to the lastest 2 hubitat updates in the last week. I've also updated to your lastest driver and still seeing the problem. Thx.

**Comment by bmcgair** [comment]
also: Content is not allowed in prolog. on line 329

**Comment by erocm123** [comment]
Module needed a reboot.
